# Generated by Django 4.2.2 on 2023-07-28 10:17

from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.PositiveSmallIntegerField(validators=[registration.validators.validate_positive_number], verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[registration.validators.validate_password], verbose_name='password'),
        ),
    ]
